CREATE TABLE BOOKS (
                       id INTEGER PRIMARY KEY AUTOINCREMENT,
                       title TEXT NOT NULL,
                       author TEXT NOT NULL,
                       year INTEGER
);

insert into BOOKS (id, title, author, year) values (1, 'penatibus et magnis dis', 'Dorree Maud', '31/10/2023');
insert into BOOKS (id, title, author, year) values (2, 'pede posuere', 'Bart Wrack', '20/10/2024');
insert into BOOKS (id, title, author, year) values (3, 'rhoncus sed vestibulum sit', 'Sari Blowers', '13/12/2022');
insert into BOOKS (id, title, author, year) values (4, 'nunc vestibulum', 'Kory Grzeszczyk', '24/3/2024');
insert into BOOKS (id, title, author, year) values (5, 'odio odio elementum', 'Jerrylee Dudeney', '12/3/2023');
insert into BOOKS (id, title, author, year) values (6, 'posuere cubilia curae', 'Ricca Portt', '8/10/2022');
insert into BOOKS (id, title, author, year) values (7, 'eget congue eget', 'Davina Dederich', '6/6/2024');
insert into BOOKS (id, title, author, year) values (8, 'risus semper porta', 'Jeno Glandon', '7/4/2023');
insert into BOOKS (id, title, author, year) values (9, 'id pretium iaculis', 'Lexi Wimmer', '27/6/2023');
insert into BOOKS (id, title, author, year) values (10, 'eget tempus', 'Miner Hauck', '12/1/2024');
insert into BOOKS (id, title, author, year) values (11, 'quam fringilla rhoncus', 'Arliene Quadri', '10/8/2024');
insert into BOOKS (id, title, author, year) values (12, 'id ligula suspendisse', 'Dre Serris', '23/10/2024');
insert into BOOKS (id, title, author, year) values (13, 'tristique est et', 'Oliy Cool', '23/8/2024');
insert into BOOKS (id, title, author, year) values (14, 'cras non', 'Delora Oran', '17/9/2022');
insert into BOOKS (id, title, author, year) values (15, 'morbi porttitor', 'Liane Cruickshanks', '23/9/2023');
insert into BOOKS (id, title, author, year) values (16, 'metus sapien ut', 'Vera Yurasov', '24/5/2023');
insert into BOOKS (id, title, author, year) values (17, 'sed lacus morbi sem', 'Jamaal MacSwayde', '29/10/2024');
insert into BOOKS (id, title, author, year) values (18, 'luctus rutrum nulla tellus', 'Dirk Caley', '31/1/2024');
insert into BOOKS (id, title, author, year) values (19, 'consequat lectus in est', 'Merrill Grange', '26/6/2024');
insert into BOOKS (id, title, author, year) values (20, 'id nisl venenatis', 'Sukey Gossage', '3/1/2024');
insert into BOOKS (id, title, author, year) values (21, 'condimentum curabitur', 'Tansy Torrejon', '28/4/2024');
insert into BOOKS (id, title, author, year) values (22, 'aenean fermentum donec', 'Marylin Bettley', '2/9/2022');
insert into BOOKS (id, title, author, year) values (23, 'platea dictumst etiam', 'Klarrisa Penniall', '24/12/2022');
insert into BOOKS (id, title, author, year) values (24, 'lectus aliquam sit', 'Kenyon O''Sheeryne', '23/4/2024');
insert into BOOKS (id, title, author, year) values (25, 'ante ipsum primis in', 'Wandie Manes', '26/11/2024');
insert into BOOKS (id, title, author, year) values (26, 'lectus suspendisse', 'Alia McGillivrie', '4/12/2022');
insert into BOOKS (id, title, author, year) values (27, 'metus aenean fermentum', 'Gisella Stichall', '23/3/2023');
insert into BOOKS (id, title, author, year) values (28, 'vestibulum ante ipsum primis', 'Xylia McGonagle', '5/8/2023');
insert into BOOKS (id, title, author, year) values (29, 'quis tortor id', 'Bale Bushrod', '28/8/2022');
insert into BOOKS (id, title, author, year) values (30, 'non ligula', 'Felicle Becket', '21/4/2023');
insert into BOOKS (id, title, author, year) values (31, 'vestibulum velit id', 'Marty Foux', '29/10/2023');
insert into BOOKS (id, title, author, year) values (32, 'vestibulum ante ipsum', 'Olivier Harly', '13/1/2024');
insert into BOOKS (id, title, author, year) values (33, 'pellentesque quisque', 'Aigneis Frosdick', '17/4/2023');
insert into BOOKS (id, title, author, year) values (34, 'vestibulum ac est', 'Noemi Gaukroger', '15/11/2024');
insert into BOOKS (id, title, author, year) values (35, 'ligula vehicula consequat', 'Myca Luebbert', '24/2/2024');
insert into BOOKS (id, title, author, year) values (36, 'ut odio', 'Jacob Davys', '5/1/2024');
insert into BOOKS (id, title, author, year) values (37, 'felis sed interdum', 'Roxy Bigly', '1/9/2023');
insert into BOOKS (id, title, author, year) values (38, 'cursus id turpis', 'Claudelle McGucken', '23/1/2024');
insert into BOOKS (id, title, author, year) values (39, 'nunc viverra', 'Adelice Gerrans', '17/10/2022');
insert into BOOKS (id, title, author, year) values (40, 'nulla ut erat', 'Sarine Van Dijk', '22/2/2024');
insert into BOOKS (id, title, author, year) values (41, 'amet eleifend pede', 'Patrizia Hasty', '12/10/2023');
insert into BOOKS (id, title, author, year) values (42, 'diam nam', 'Nettle Cogley', '30/8/2022');
insert into BOOKS (id, title, author, year) values (43, 'pellentesque ultrices phasellus id', 'Erick Firidolfi', '21/4/2023');
insert into BOOKS (id, title, author, year) values (44, 'aliquam sit', 'Kippy Brockherst', '2/9/2024');
insert into BOOKS (id, title, author, year) values (45, 'sit amet', 'Rikki Purtell', '17/6/2023');
insert into BOOKS (id, title, author, year) values (46, 'amet consectetuer', 'Catie Ginie', '30/11/2022');
insert into BOOKS (id, title, author, year) values (47, 'vel pede', 'Rudie Caress', '8/4/2023');
insert into BOOKS (id, title, author, year) values (48, 'condimentum curabitur in libero', 'Ronny Hixley', '18/6/2024');
insert into BOOKS (id, title, author, year) values (49, 'ac est lacinia', 'Irwinn Crepin', '1/12/2023');
insert into BOOKS (id, title, author, year) values (50, 'quisque ut erat curabitur', 'Margery Peotz', '14/10/2023');
insert into BOOKS (id, title, author, year) values (51, 'vestibulum rutrum rutrum neque', 'Everett Wickliffe', '31/12/2023');
insert into BOOKS (id, title, author, year) values (52, 'tristique in tempus', 'Lynnelle Linwood', '22/12/2023');
insert into BOOKS (id, title, author, year) values (53, 'dis parturient montes nascetur', 'Tiffie Nugent', '14/5/2023');
insert into BOOKS (id, title, author, year) values (54, 'sapien iaculis congue vivamus', 'Keslie Hafner', '7/4/2023');
insert into BOOKS (id, title, author, year) values (55, 'dolor sit amet', 'Alfreda Delos', '30/1/2024');
insert into BOOKS (id, title, author, year) values (56, 'ligula in', 'Frannie Graysmark', '8/12/2022');
insert into BOOKS (id, title, author, year) values (57, 'urna pretium nisl', 'Joseph Sterland', '22/7/2023');
insert into BOOKS (id, title, author, year) values (58, 'non ligula pellentesque', 'Ellen Edmonstone', '19/9/2024');
insert into BOOKS (id, title, author, year) values (59, 'sit amet', 'Ruttger Burcher', '16/7/2022');
insert into BOOKS (id, title, author, year) values (60, 'justo nec condimentum neque', 'Miles Tinto', '7/3/2023');
insert into BOOKS (id, title, author, year) values (61, 'turpis donec posuere', 'Felic Vedeshkin', '14/9/2023');
insert into BOOKS (id, title, author, year) values (62, 'est congue', 'Ulrika Balazot', '21/8/2024');
insert into BOOKS (id, title, author, year) values (63, 'at dolor quis odio', 'Emylee Saphin', '6/1/2023');
insert into BOOKS (id, title, author, year) values (64, 'sagittis dui vel nisl', 'Jerrome Balden', '25/10/2024');
insert into BOOKS (id, title, author, year) values (65, 'consequat in', 'Daniele Jeannon', '5/10/2022');
insert into BOOKS (id, title, author, year) values (66, 'vivamus vel', 'Ricki Gilyott', '29/4/2023');
insert into BOOKS (id, title, author, year) values (67, 'morbi porttitor', 'Georgine Mountcastle', '27/7/2022');
insert into BOOKS (id, title, author, year) values (68, 'rutrum at lorem', 'Pauly Botterell', '9/3/2024');
insert into BOOKS (id, title, author, year) values (69, 'nulla justo aliquam quis', 'Holmes Rosenstengel', '3/7/2023');
insert into BOOKS (id, title, author, year) values (70, 'sociis natoque', 'Shurlocke Fruchon', '11/2/2024');
insert into BOOKS (id, title, author, year) values (71, 'eget eros', 'Marilin McVey', '27/5/2024');
insert into BOOKS (id, title, author, year) values (72, 'condimentum curabitur', 'Micah Devonside', '13/9/2024');
insert into BOOKS (id, title, author, year) values (73, 'sit amet sem fusce', 'Charlotte Pendlington', '2/2/2023');
insert into BOOKS (id, title, author, year) values (74, 'vestibulum ante ipsum', 'Rebeka Santori', '14/6/2024');
insert into BOOKS (id, title, author, year) values (75, 'at lorem', 'Kellie Langton', '8/12/2022');
insert into BOOKS (id, title, author, year) values (76, 'donec vitae nisi nam', 'Georgie Tuff', '15/7/2022');
insert into BOOKS (id, title, author, year) values (77, 'vulputate justo in', 'Roberto Pretious', '27/7/2024');
insert into BOOKS (id, title, author, year) values (78, 'ut ultrices vel', 'Zeke Simonin', '22/5/2023');
insert into BOOKS (id, title, author, year) values (79, 'condimentum id', 'Denyse McQueen', '4/9/2024');
insert into BOOKS (id, title, author, year) values (80, 'tortor risus', 'Warde Bruins', '30/9/2023');
insert into BOOKS (id, title, author, year) values (81, 'mollis molestie lorem quisque', 'Brandtr Dehmel', '30/1/2024');
insert into BOOKS (id, title, author, year) values (82, 'congue etiam justo', 'Davine Potkin', '27/1/2024');
insert into BOOKS (id, title, author, year) values (83, 'nulla nisl', 'Lucie Ringsell', '15/5/2023');
insert into BOOKS (id, title, author, year) values (84, 'ante nulla', 'Erinna Gealle', '6/8/2022');
insert into BOOKS (id, title, author, year) values (85, 'eget massa tempor', 'Feliks Ipsley', '5/7/2022');
insert into BOOKS (id, title, author, year) values (86, 'integer a nibh in', 'Tracy Aisman', '2/8/2024');
insert into BOOKS (id, title, author, year) values (87, 'egestas metus', 'Rudd Gun', '20/1/2023');
insert into BOOKS (id, title, author, year) values (88, 'sapien arcu sed', 'Doll Ladbrook', '15/9/2023');
insert into BOOKS (id, title, author, year) values (89, 'vivamus vestibulum sagittis sapien', 'Ranna Casperri', '31/8/2024');
insert into BOOKS (id, title, author, year) values (90, 'in leo', 'Shantee Hinkley', '31/10/2023');
insert into BOOKS (id, title, author, year) values (91, 'donec ut mauris', 'Adelice Somes', '18/6/2023');
insert into BOOKS (id, title, author, year) values (92, 'erat vestibulum sed magna', 'Josi Mattheus', '21/11/2024');
insert into BOOKS (id, title, author, year) values (93, 'nibh ligula nec', 'Tudor Gardner', '11/7/2024');
insert into BOOKS (id, title, author, year) values (94, 'orci luctus', 'Bobette Cricket', '14/7/2023');
insert into BOOKS (id, title, author, year) values (95, 'amet justo morbi ut', 'Padraic Haggis', '17/11/2022');
insert into BOOKS (id, title, author, year) values (96, 'mauris enim leo rhoncus', 'Desmund Van T''Hoog', '8/8/2022');
insert into BOOKS (id, title, author, year) values (97, 'pede justo eu massa', 'Sally Critzen', '1/3/2024');
insert into BOOKS (id, title, author, year) values (98, 'lobortis sapien sapien', 'Caresa Hansberry', '21/1/2024');
insert into BOOKS (id, title, author, year) values (99, 'convallis nunc proin', 'Ailene Rivallant', '7/5/2023');
insert into BOOKS (id, title, author, year) values (100, 'tempus vel pede morbi', 'Daryl Antoniak', '25/4/2024');
